### ISSUE TITLE
Type conversion between custom type and ARRAY

### ISSUE THREAD

**Issue by mookjp** [cloudspannerecosystem/yo#41]
Hi, I'd like to generate code with `ARRAY(INT64)` with custom types.

If I write DDL and custom types configuration like this:

```
# sql
CREATE TABLE Items (
  Codes ARRAY<INT64> NOT NULL,
// ...
```

```
# custom_column_types.yml
tables:
  - name: Items
    columns:
      Codes: Codes
// or might be
//    Codes: "[]Code"
```

```
// type.go

type Codes []Code
type Code int64

const (
  CodeOK Code = 1
  CodeNG Code = 2
)
```

I want to generate code with conversion between the type (e,g, `INT64`) and custom type (e.g. `Code`) if it is an array.
The default template shows it has condition to check `Field` has `CustomType` or not so that it generates type conversion code.
It would be helpful to have the method to know the field type is `ARRAY` or not in this case, but do you have any idea or suggestion for this?

```
// type.go.tpl

	{{- range .Fields }}
		{{- if .CustomType.IsArray }}
			// type conversion code for array type
		{{- end }}
	{{- end }}
```
